title: TechGuy's Learning Hub
description: Personal notes on Computer Science algorithms and Duolingo language learning
author: TechGuy
email: your-email@example.com
url: "https://khoatcao.github.io"
baseurl: "/TechGuy.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
