title: TechGuy's Learning Hub
description: Personal notes on Computer Science algorithms and Duolingo language learning
author: TechGuy
email: your-email@example.com
url: "https://techguy.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
